### ISSUE TITLE
Point /groups/get-a-website to github.com/rtcharity/lean-site-template

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#521] opened 2019-03-29 10:09 UTC
Based on 

> Referrer: https://effektiveraltruismus.de Requested URL: /groups/get-a-website User agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0) IP address: 149.126.4.71, 162.158.150.57:28966

**Comment by taymonbeal** [comment] 2019-04-16 00:29
Duplicate of #609.

**Closed by taymonbeal** 2019-04-16 00:29 UTC
Labels: 404
