### ISSUE TITLE
Ability for users to become members of groups

### ISSUE THREAD

**Issue by Manoj-nathwani** [rtcharity/eahub.org#249] opened 2019-02-15 02:45 UTC
# Problem
- Today we only have the ability for users to be `organisers` of groups which means they run them however there's no way of expressing that you are a `member` of EA London meaning you just attend events and are part of the community.

# Solution
- Give users the ability to become members of groups

**Comment by michaltrzesimiech** [comment] 2019-02-27 00:59
Duplicate of https://github.com/rtcharity/eahub.org/issues/304

**Comment by taymonbeal** [comment] 2019-02-27 02:46
Becoming an organizer and becoming a member are different things from a technical perspective, so it makes sense to track them separately.

**Comment by sebgrebe** [comment] 2019-03-03 17:35
Implemented this as follows:
* Users goes to community/edit page
![screen shot 2019-03-03 at 17 32 25](https://user-images.githubusercontent.com/15908208/53698899-811f7c80-3dda-11e9-80b8-f4c79e647c38.png)
* User clicks on multiselect button
![screen shot 2019-03-03 at 17 32 31](https://user-images.githubusercontent.com/15908208/53698907-8ed50200-3dda-11e9-80b7-44f1141cf83a.png)
* User choses their local group and update (a user can choose more than one group)
![screen shot 2019-03-03 at 17 32 38](https://user-images.githubusercontent.com/15908208/53698912-998f9700-3dda-11e9-81b5-5b99c92061de.png)
* User's group appears alongside their organisational affiliation on their community card
![screen shot 2019-03-03 at 17 33 06](https://user-images.githubusercontent.com/15908208/53698923-add39400-3dda-11e9-95a7-9ffc20da66c7.png)

**Comment by michaltrzesimiech** [comment] 2019-03-04 20:12
Thanks, Seb! @Richenda will have to have her say on this

**Comment by Richenda** [comment] 2019-03-04 22:35
Hey @sebgrebe is there a question in those posts or are you just reporting on how you are solving this problem, so that we can give feedback?

From what I understood that looks great. If I missed a further question, just tag me.

**Comment by sebgrebe** [comment] 2019-03-05 20:57
> From what I understood that looks great. If I missed a further question, just tag me.

Cool :) This is in code review, should be visible tomorrow.

**Closed** 2019-03-06 00:08 UTC
Labels: Database, Feature Request, High Priority, In Progress, UX
