### ISSUE TITLE
Changes to meta tags and title

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#895] opened 2020-04-07 08:29 UTC
<title>Effective Altruism Hub</title>

    <meta name="description" content="{{ slogan }}">
    <meta name="keywords" content="HTML,CSS,JavaScript">
    <meta property="og:url"           content="https://eahub.org" />
    <meta property="og:type"          content="website" />
    <meta property="og:title"         content="Effective Altruism Hub" />
    <meta property="og:image"         content="/img/image.png" />
    <link rel="canonical" href="https://eahub.org" />

**Comment by victor-yunenko** [comment] 2020-11-08 16:55
closing since I guess it's a duplicate of #920?

**Closed by victor-yunenko** 2020-11-08 16:55 UTC
